version: '3.3'

services:
  postgres:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=admin123
      - MYSQL_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
