version: '3.3'

services:
  postgres:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5050:80

